"""add learner progress table.

Revision ID: a7f3c9e21b04
Revises: bf3cac30a0c5
Create Date: 2026-08-01 15:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7f3c9e21b04"
down_revision: Union[str, Sequence[str], None] = "bf3cac30a0c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learnerprogressrecord",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cohort_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("as_of", sa.DateTime(), nullable=False),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column("missed_deadlines", sa.Integer(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("recent_feedback_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_learnerprogressrecord_learner_id"), "learnerprogressrecord", ["learner_id"], unique=False)
    op.create_index(op.f("ix_learnerprogressrecord_cohort_id"), "learnerprogressrecord", ["cohort_id"], unique=False)
    op.create_index(
        "uq_learnerprogressrecord_learner_id",
        "learnerprogressrecord",
        ["learner_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_learnerprogressrecord_learner_id", table_name="learnerprogressrecord")
    op.drop_index(op.f("ix_learnerprogressrecord_cohort_id"), table_name="learnerprogressrecord")
    op.drop_index(op.f("ix_learnerprogressrecord_learner_id"), table_name="learnerprogressrecord")
    op.drop_table("learnerprogressrecord")
    # ### end Alembic commands ###
