"""add reminder_event table.

Revision ID: fdaea123798d
Revises: cf0499e7ef1e
Create Date: 2026-07-24 12:51:34.613787

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "fdaea123798d"
down_revision: Union[str, Sequence[str], None] = "cf0499e7ef1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminderevent",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
        "type",
        postgresql.ENUM(
            "SESSION_REMINDER",
            "DEADLINE_REMINDER",
            "AT_RISK_NUDGE",
            "FEEDBACK_FOLLOWUP",
            name="notificationtype",
            create_type=False,
        ),
        nullable=False,
    ),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminderevent_due_at"), "reminderevent", ["due_at"], unique=False)
    op.create_index(op.f("ix_reminderevent_recipient_id"), "reminderevent", ["recipient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminderevent_recipient_id"), table_name="reminderevent")
    op.drop_index(op.f("ix_reminderevent_due_at"), table_name="reminderevent")
    op.drop_table("reminderevent")
    # ### end Alembic commands ###
